#!/usr/bin/env php
# autogenerated file; do not edit
sudo: false
language: c

addons:
 apt:
  packages:
   - php5-cli
   - php-pear

env:
<?php
$gen = include "./travis/pecl/gen-matrix.php";
$cur = "7.3";
$env = $gen([
	"PHP" => ["7.0", "7.1", "7.2", "master"],
	"enable_debug" => "yes",
	"enable_maintainer_zts" => "yes",
	"enable_json" => "yes",
], [
	"PHP" => $cur,
	"enable_json" => "yes",
	"enable_debug",
	"enable_maintainer_zts"
], [
	"PHP" => $cur,
	"enable_json" => "yes",
	"CFLAGS" => "'-O0 -g --coverage'",
	"CXXFLAGS" => "'-O0 -g --coverage'",
]);

foreach ($env as $g) {
	foreach ($g as $e) {
		printf(" - %s\n", $e);
	}
}
?>

matrix:
 fast_finish: true
 allow_failures:
<?php
$allow_failures = array_merge( ... array_map(function($a) {
	return preg_grep('/^PHP=master /', $a);
}, $env));
foreach ($allow_failures as $e) {
	printf("  - env: %s\n", $e);
}
?>

before_script:
 - make -f travis/pecl/Makefile php
 - make -f travis/pecl/Makefile ext PECL=propro

script:
 - make -f travis/pecl/Makefile test

after_success:
 - test -n "$CFLAGS" && cd src/.libs && bash <(curl -s https://codecov.io/bash) -X xcode -X coveragepy
